import {
  dispatchOpenCreateChapter,
  dispatchOpenCreateCharacter,
  dispatchOpenCreateEvent,
  dispatchOpenCreateNote,
  dispatchOpenCreateObject,
  dispatchOpenCreatePart,
  dispatchOpenCreatePlace,
  dispatchOpenCreateResearch,
  dispatchOpenDeleteSelectedChapter,
  dispatchOpenDeleteSelectedCharacter,
  dispatchOpenDeleteSelectedEvent,
  dispatchOpenDeleteSelectedNote,
  dispatchOpenDeleteSelectedObject,
  dispatchOpenDeleteSelectedPart,
  dispatchOpenDeleteSelectedPlace,
  dispatchOpenEditSelectedChapter,
  dispatchOpenEditSelectedCharacter,
  dispatchOpenEditSelectedEvent,
  dispatchOpenEditSelectedNote,
  dispatchOpenEditSelectedObject,
  dispatchOpenEditSelectedPart,
  dispatchOpenEditSelectedPlace,
  dispatchOpenEditStructure,
  openCreateChapterEvent,
  openCreateCharacterEvent,
  openCreateEventEvent,
  openCreateNoteEvent,
  openCreateObjectEvent,
  openCreatePartEvent,
  openCreatePlaceEvent,
  openCreateResearchEvent,
  openDeleteSelectedChapterEvent,
  openDeleteSelectedCharacterEvent,
  openDeleteSelectedEventEvent,
  openDeleteSelectedNoteEvent,
  openDeleteSelectedObjectEvent,
  openDeleteSelectedPartEvent,
  openDeleteSelectedPlaceEvent,
  openEditSelectedChapterEvent,
  openEditSelectedCharacterEvent,
  openEditSelectedEventEvent,
  openEditSelectedNoteEvent,
  openEditSelectedObjectEvent,
  openEditSelectedPartEvent,
  openEditSelectedPlaceEvent,
  openEditStructureEvent,
} from "../../../apps/desktop/src/utils/shortcut-events";

describe("shortcut events", () => {
  it.each([
    [openCreatePartEvent, dispatchOpenCreatePart],
    [openCreateChapterEvent, dispatchOpenCreateChapter],
    [openCreateCharacterEvent, dispatchOpenCreateCharacter],
    [openCreatePlaceEvent, dispatchOpenCreatePlace],
    [openCreateObjectEvent, dispatchOpenCreateObject],
    [openCreateResearchEvent, dispatchOpenCreateResearch],
    [openCreateEventEvent, dispatchOpenCreateEvent],
    [openCreateNoteEvent, dispatchOpenCreateNote],
    [openEditSelectedCharacterEvent, dispatchOpenEditSelectedCharacter],
    [openDeleteSelectedCharacterEvent, dispatchOpenDeleteSelectedCharacter],
    [openEditSelectedPlaceEvent, dispatchOpenEditSelectedPlace],
    [openDeleteSelectedPlaceEvent, dispatchOpenDeleteSelectedPlace],
    [openEditSelectedObjectEvent, dispatchOpenEditSelectedObject],
    [openDeleteSelectedObjectEvent, dispatchOpenDeleteSelectedObject],
    [openEditSelectedEventEvent, dispatchOpenEditSelectedEvent],
    [openDeleteSelectedEventEvent, dispatchOpenDeleteSelectedEvent],
    [openEditSelectedNoteEvent, dispatchOpenEditSelectedNote],
    [openDeleteSelectedNoteEvent, dispatchOpenDeleteSelectedNote],
    [openEditSelectedPartEvent, dispatchOpenEditSelectedPart],
    [openDeleteSelectedPartEvent, dispatchOpenDeleteSelectedPart],
    [openEditSelectedChapterEvent, dispatchOpenEditSelectedChapter],
    [openDeleteSelectedChapterEvent, dispatchOpenDeleteSelectedChapter],
    [openEditStructureEvent, dispatchOpenEditStructure],
  ])("dispatches %s", (eventName, dispatch) => {
    const listener = jest.fn();
    window.addEventListener(eventName, listener);

    dispatch();

    expect(listener).toHaveBeenCalledTimes(1);
  });
});
