import { Migration } from '@mikro-orm/migrations';

export class Migration20260228153406 extends Migration {

  override async up(): Promise<void> {
    this.addSql(`alter table "character_entity" alter column "nationality" type varchar(255) using ("nationality"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "nationality" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "birth_place" type varchar(255) using ("birth_place"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "birth_place" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "residence_place" type varchar(255) using ("residence_place"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "residence_place" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "occupation" type varchar(255) using ("occupation"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "occupation" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "height" type int using ("height"::int);`);
    this.addSql(`alter table "character_entity" alter column "height" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "weight" type int using ("weight"::int);`);
    this.addSql(`alter table "character_entity" alter column "weight" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "corpulence" type varchar(255) using ("corpulence"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "corpulence" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "hair_color" type varchar(255) using ("hair_color"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "hair_color" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "eyes_color" type varchar(255) using ("eyes_color"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "eyes_color" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "voice" type varchar(255) using ("voice"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "voice" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "outfit" type varchar(255) using ("outfit"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "outfit" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "accessory" type varchar(255) using ("accessory"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "accessory" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "character_qualities" type text[] using ("character_qualities"::text[]);`);
    this.addSql(`alter table "character_entity" alter column "character_qualities" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "character_flaws" type text[] using ("character_flaws"::text[]);`);
    this.addSql(`alter table "character_entity" alter column "character_flaws" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "tastes" type varchar(255) using ("tastes"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "tastes" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "tics" type varchar(255) using ("tics"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "tics" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "fears" type varchar(255) using ("fears"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "fears" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "education" type varchar(255) using ("education"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "education" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "richesses" type int using ("richesses"::int);`);
    this.addSql(`alter table "character_entity" alter column "richesses" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "belief" type varchar(255) using ("belief"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "belief" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "secrets" type varchar(255) using ("secrets"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "secrets" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "notable_places" type varchar(255) using ("notable_places"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "notable_places" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "typical_expression" type varchar(255) using ("typical_expression"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "typical_expression" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "goals" type varchar(255) using ("goals"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "goals" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "past" type varchar(255) using ("past"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "past" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "present" type varchar(255) using ("present"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "present" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "future" type varchar(255) using ("future"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "future" drop not null;`);
    this.addSql(`alter table "character_entity" alter column "notes" type text using ("notes"::text);`);
    this.addSql(`alter table "character_entity" alter column "notes" drop not null;`);
  }

  override async down(): Promise<void> {
    this.addSql(`alter table "character_entity" alter column "nationality" type varchar(255) using ("nationality"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "nationality" set not null;`);
    this.addSql(`alter table "character_entity" alter column "birth_place" type varchar(255) using ("birth_place"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "birth_place" set not null;`);
    this.addSql(`alter table "character_entity" alter column "residence_place" type varchar(255) using ("residence_place"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "residence_place" set not null;`);
    this.addSql(`alter table "character_entity" alter column "occupation" type varchar(255) using ("occupation"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "occupation" set not null;`);
    this.addSql(`alter table "character_entity" alter column "height" type int using ("height"::int);`);
    this.addSql(`alter table "character_entity" alter column "height" set not null;`);
    this.addSql(`alter table "character_entity" alter column "weight" type int using ("weight"::int);`);
    this.addSql(`alter table "character_entity" alter column "weight" set not null;`);
    this.addSql(`alter table "character_entity" alter column "corpulence" type varchar(255) using ("corpulence"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "corpulence" set not null;`);
    this.addSql(`alter table "character_entity" alter column "hair_color" type varchar(255) using ("hair_color"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "hair_color" set not null;`);
    this.addSql(`alter table "character_entity" alter column "eyes_color" type varchar(255) using ("eyes_color"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "eyes_color" set not null;`);
    this.addSql(`alter table "character_entity" alter column "voice" type varchar(255) using ("voice"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "voice" set not null;`);
    this.addSql(`alter table "character_entity" alter column "outfit" type varchar(255) using ("outfit"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "outfit" set not null;`);
    this.addSql(`alter table "character_entity" alter column "accessory" type varchar(255) using ("accessory"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "accessory" set not null;`);
    this.addSql(`alter table "character_entity" alter column "character_qualities" type text[] using ("character_qualities"::text[]);`);
    this.addSql(`alter table "character_entity" alter column "character_qualities" set not null;`);
    this.addSql(`alter table "character_entity" alter column "character_flaws" type text[] using ("character_flaws"::text[]);`);
    this.addSql(`alter table "character_entity" alter column "character_flaws" set not null;`);
    this.addSql(`alter table "character_entity" alter column "tastes" type varchar(255) using ("tastes"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "tastes" set not null;`);
    this.addSql(`alter table "character_entity" alter column "tics" type varchar(255) using ("tics"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "tics" set not null;`);
    this.addSql(`alter table "character_entity" alter column "fears" type varchar(255) using ("fears"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "fears" set not null;`);
    this.addSql(`alter table "character_entity" alter column "education" type varchar(255) using ("education"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "education" set not null;`);
    this.addSql(`alter table "character_entity" alter column "richesses" type int using ("richesses"::int);`);
    this.addSql(`alter table "character_entity" alter column "richesses" set not null;`);
    this.addSql(`alter table "character_entity" alter column "belief" type varchar(255) using ("belief"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "belief" set not null;`);
    this.addSql(`alter table "character_entity" alter column "secrets" type varchar(255) using ("secrets"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "secrets" set not null;`);
    this.addSql(`alter table "character_entity" alter column "notable_places" type varchar(255) using ("notable_places"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "notable_places" set not null;`);
    this.addSql(`alter table "character_entity" alter column "typical_expression" type varchar(255) using ("typical_expression"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "typical_expression" set not null;`);
    this.addSql(`alter table "character_entity" alter column "goals" type varchar(255) using ("goals"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "goals" set not null;`);
    this.addSql(`alter table "character_entity" alter column "past" type varchar(255) using ("past"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "past" set not null;`);
    this.addSql(`alter table "character_entity" alter column "present" type varchar(255) using ("present"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "present" set not null;`);
    this.addSql(`alter table "character_entity" alter column "future" type varchar(255) using ("future"::varchar(255));`);
    this.addSql(`alter table "character_entity" alter column "future" set not null;`);
    this.addSql(`alter table "character_entity" alter column "notes" type text using ("notes"::text);`);
    this.addSql(`alter table "character_entity" alter column "notes" set not null;`);
  }

}
